# This file will build binaries for a tag (or tagged release). If you don't
# create a release with your tag it will create one for you.
name: Tag Build
on:
  push:
    tags:
      - "*"

jobs:
  build-dev:
    uses: ./.github/workflows/cross-platform-build.yml
    name: Build against Binary Ninja Dev
    with:
      # Should match project(name_here) from CMakeLists.txt
      project_name: binja_printk
      artifact_prefix: dev
      binaryninja_api_path: vendor/api

  build-stable:
    uses: ./.github/workflows/cross-platform-build.yml
    name: Build against Binary Ninja Stable
    with:
      # Should match project(name_here) from CMakeLists.txt
      project_name: binja_printk
      artifact_prefix: stable
      binaryninja_api_path: vendor/api-stable

  make-release:
    needs: [ build-dev, build-stable ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # We checkout the whole repo so that git describe works. There's
          # probably a more performant way, but most plugins are small so this
          # should be fine.
          fetch-depth: 0

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Check files present
        run: |-
          cd artifacts
          ls -Fhl
          find .
      - name: Consolidate and rename files for release
        run: |-
          cd artifacts
          ${{github.workspace}}/scripts/tidy_release.bash dev stable
          find .
      - name: Release
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        working-directory: "${{github.workspace}}/artifacts"
        # We only overwrite the name if the release doesn't already exist
        run: |-
          ${{github.workspace}}/scripts/do_release.py --title "Release" --tag $GITHUB_REF_NAME --artifacts release
